name: Build

on: [ push ]
env:
  PACKAGE_VERSION: 1.0.16

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set assembly version
        run: "echo ASSEMBLY_VERSION=\"$env:PACKAGE_VERSION.$env:GITHUB_RUN_NUMBER\" >> $env:GITHUB_ENV"
      - name: Set continuous package version
        if: ${{ github.ref == 'refs/heads/main' }}
        run: "echo PACKAGE_VERSION=\"$env:PACKAGE_VERSION$(Get-Date -f \"-yyyyMMdd-hhmmss\")\" >> $env:GITHUB_ENV"
      - run: |
          echo "assembly version: $env:ASSEMBLY_VERSION"
          echo "package version: $env:PACKAGE_VERSION"
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:AssemblyVersion=$env:ASSEMBLY_VERSION
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Pack
        run: dotnet pack --configuration Release --no-build /p:PackageVersion=$env:PACKAGE_VERSION /p:AssemblyVersion=$env:ASSEMBLY_VERSION
      - name: Push to nuget.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push nugets/DeepCopy.Fody.$env:PACKAGE_VERSION.nupkg --source https://api.nuget.org/v3/index.json --api-key $env:NUGET_API_KEY