name: dotnet package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      PACKAGE_VERSION: 1.0.15
      ASSEMBLY_VERSION: ${{ jobs.build.env.PACKAGE_VERSION }}.${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:AssemblyVersion=%ASSEMBLY_VERSION%
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Package
        run: dotnet pack --configuration Release /p:PackageVersion=%PACKAGE_VERSION% /p:AssemblyVersion=%ASSEMBLY_VERSION%